
# asp_py_parsetab.py
# This file is automatically generated. Do not edit.
_tabversion = '3.2'

_lr_method = 'LALR'

_lr_signature = b'H<\t\xc8tV\xb4?\x0e/8*\xe5\xcc\x8a\x82'
    
_lr_action_items = {'STRING':([6,7,16,17,],[13,13,13,13,]),'SPACE':([1,2,3,15,18,],[5,-4,-6,-3,-5,]),'LP':([2,3,12,],[6,7,17,]),'NUM':([6,7,16,17,],[11,11,11,11,]),'IDENT':([0,5,6,7,16,17,],[2,2,12,12,12,12,]),'COMMA':([10,11,12,13,21,],[16,-12,-11,-10,-9,]),'MIDENT':([0,5,],[3,3,]),'RP':([9,10,11,12,13,14,19,20,21,],[15,-8,-12,-11,-10,18,-7,21,-9,]),'$end':([1,2,3,4,8,15,18,],[-2,-4,-6,0,-1,-3,-5,]),}

_lr_action = { }
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = { }
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'atom':([0,5,],[1,1,]),'terms':([6,7,16,17,],[9,14,19,20,]),'term':([6,7,16,17,],[10,10,10,10,]),'answerset':([0,5,],[4,8,]),}

_lr_goto = { }
for _k, _v in _lr_goto_items.items():
   for _x,_y in zip(_v[0],_v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = { }
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> answerset","S'",1,None,None,None),
  ('answerset -> atom SPACE answerset','answerset',3,'p_answerset','/home/sergey/.local/lib/python3.4/site-packages/pyasp/asp.py',188),
  ('answerset -> atom','answerset',1,'p_answerset','/home/sergey/.local/lib/python3.4/site-packages/pyasp/asp.py',189),
  ('atom -> IDENT LP terms RP','atom',4,'p_atom','/home/sergey/.local/lib/python3.4/site-packages/pyasp/asp.py',194),
  ('atom -> IDENT','atom',1,'p_atom','/home/sergey/.local/lib/python3.4/site-packages/pyasp/asp.py',195),
  ('atom -> MIDENT LP terms RP','atom',4,'p_atom','/home/sergey/.local/lib/python3.4/site-packages/pyasp/asp.py',196),
  ('atom -> MIDENT','atom',1,'p_atom','/home/sergey/.local/lib/python3.4/site-packages/pyasp/asp.py',197),
  ('terms -> term COMMA terms','terms',3,'p_terms','/home/sergey/.local/lib/python3.4/site-packages/pyasp/asp.py',211),
  ('terms -> term','terms',1,'p_terms','/home/sergey/.local/lib/python3.4/site-packages/pyasp/asp.py',212),
  ('term -> IDENT LP terms RP','term',4,'p_term','/home/sergey/.local/lib/python3.4/site-packages/pyasp/asp.py',220),
  ('term -> STRING','term',1,'p_term','/home/sergey/.local/lib/python3.4/site-packages/pyasp/asp.py',221),
  ('term -> IDENT','term',1,'p_term','/home/sergey/.local/lib/python3.4/site-packages/pyasp/asp.py',222),
  ('term -> NUM','term',1,'p_term','/home/sergey/.local/lib/python3.4/site-packages/pyasp/asp.py',223),
]
